### ISSUE TITLE
No handling for key-value objects

### ISSUE THREAD

**Issue by wyqydsyq** [mattdesl/select-box#2]
Should be able to do this:

``` js
var box = SelectBox({
    hello: 'Hello!',
    goodbye: 'Goodbye!'
});
```

Which should result in this when you `console.log(box.element.outerHTML);`:

``` html
<select>
    <option value="hello">Hello!</option>
    <option value="goodbye">Goodbye!</option>
</select>
```

**Comment by mattdesl** [comment]
Cool, I'll merge but I suppose docs will need updating. :) I can make you a contributor of this module
